# Generated by Django 2.2.4 on 2019-12-09 04:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='emission',
            name='cover',
            field=models.ImageField(null=True, upload_to='uploads/images/2019/12/09/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='www.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(null=True, upload_to='uploads/images/2019/12/09/'),
        ),
        migrations.AlterField(
            model_name='season',
            name='ending_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 17, 4, 10, 24, 698785, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='week',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 16, 4, 10, 24, 700458, tzinfo=utc)),
        ),
    ]
