# Generated by Django 2.2.2 on 2019-07-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("www", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="cover",
            field=models.ImageField(null=True, upload_to="uploads/images/2019/07/12/"),
        )
    ]
