# Generated by Django 2.2.2 on 2019-07-19 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("www", "0002_auto_20190712_2034"),
    ]

    operations = [
        migrations.AddField(
            model_name="emissionsubmission",
            name="author",
            field=models.ForeignKey(
                default=0,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="emissionsubmission",
            name="description",
            field=models.CharField(default="Juna", max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="emission",
            name="cover",
            field=models.ImageField(null=True, upload_to="uploads/images/2019/07/19/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="cover",
            field=models.ImageField(null=True, upload_to="uploads/images/2019/07/19/"),
        ),
    ]
