# Generated by Django 2.2 on 2019-05-04 12:20

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_auto_20190427_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=martor.models.MartorField(),
        ),
    ]
