# Generated by Django 2.2.4 on 2019-12-10 00:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_auto_20191209_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emission',
            name='cover',
            field=models.ImageField(null=True, upload_to='uploads/images/2019/12/10/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='www.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(null=True, upload_to='uploads/images/2019/12/10/'),
        ),
        migrations.AlterField(
            model_name='season',
            name='ending_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 18, 0, 55, 7, 519719, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='week',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 0, 55, 7, 521756, tzinfo=utc)),
        ),
    ]
