# Generated by Django 2.2.2 on 2019-07-19 17:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0003_auto_20190719_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionsubmission',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='emissionsubmission',
            name='und_score_down',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emissionsubmission',
            name='und_score_up',
            field=models.IntegerField(default=0),
        ),
    ]
