# Generated by Django 2.2 on 2019-05-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0003_auto_20190504_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('portrait', models.CharField(max_length=100)),
                ('portrait_lg', models.CharField(max_length=100)),
                ('portrait_full', models.CharField(max_length=100)),
                ('portrait_vert', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(null=True, upload_to='uploads/images/2019/05/19/'),
        ),
    ]
