# Generated by Django 2.2.2 on 2019-11-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0004_auto_20190719_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emissionsubmission',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='emissionsubmission',
            name='upvotes',
        ),
        migrations.AlterField(
            model_name='emission',
            name='cover',
            field=models.ImageField(null=True, upload_to='uploads/images/2019/11/16/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(null=True, upload_to='uploads/images/2019/11/16/'),
        ),
    ]
