# Generated by Django 2.2 on 2019-05-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0004_auto_20190519_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('cost', models.IntegerField()),
                ('secret_shop', models.BooleanField()),
                ('recipe', models.BooleanField()),
                ('image', models.CharField(max_length=100)),
            ],
        ),
    ]
