# Generated by Django 2.2 on 2019-05-28 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0004_auto_20190518_2256'),
        ('www', '0005_item'),
    ]

    operations = [
    ]
