# Generated by Django 2.2.2 on 2019-11-29 11:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('www', '0005_auto_20191116_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionsubmission',
            name='downvotes',
            field=models.ManyToManyField(related_name='_emissionsubmission_downvotes_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emissionsubmission',
            name='upvotes',
            field=models.ManyToManyField(related_name='_emissionsubmission_upvotes_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emission',
            name='cover',
            field=models.ImageField(null=True, upload_to='uploads/images/2019/11/29/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(null=True, upload_to='uploads/images/2019/11/29/'),
        ),
    ]
