# Generated by Django 2.2.2 on 2019-11-29 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0006_auto_20191129_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emissionsubmission',
            name='und_score_down',
        ),
        migrations.RemoveField(
            model_name='emissionsubmission',
            name='und_score_up',
        ),
    ]
