# Generated by Django 2.2.4 on 2019-12-01 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0007_auto_20191129_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emission',
            name='cover',
            field=models.ImageField(null=True, upload_to='uploads/images/2019/12/01/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(null=True, upload_to='uploads/images/2019/12/01/'),
        ),
    ]
